// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Atoms/Button.vue')['default']
    Icon: typeof import('./src/components/Atoms/Icon.vue')['default']
    Icons: typeof import('./src/components/Atoms/Icons.vue')['default']
  }
}

export {}
